config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :challenges

  get '/created_challenges', to: 'challenges#user_created_index', as: 'user_created_challenges'
  get '/add_test_case', to: 'challenges#add_test_case'

  post '/challenges/:id/add_to_user_list', to: 'user_challenges#create', as: 'new_user_challenge'
  post '/challenges/:id/submit', to: 'user_challenges#submit', as: 'user_challenge_submit'

  delete '/challenges/:id/remove_from_user_list', to: 'user_challenges#destroy', as: 'delete_user_challenge'

  patch 'challenges/:id/update_anki_dates', to: 'user_challenges#update_anki_dates', as: 'user_challenge_update_anki_dates'
end

app/views/partials/_header.html.haml
%div.row
  %div.small-7.columns
    %h1= link_to('Interview Anki', root_path)
  %div.small-5.columns
    - if user_signed_in?
      %div.text-right
        = link_to('Logout', destroy_user_session_path, :method => :delete)
    - else
      = form_for('user', as: 'user', url: session_path('user')) do |f|
        %div.row
          %div.small-5.columns
            = f.label :email
            = f.email_field :email, autofocus: true
          %div.small-7.columns
            = f.label :password
            %div.input-group
              = f.password_field :password, { :class => 'input-group-field', autocomplete: 'off' }
              %div.input-group-button
                = f.submit 'Login', { class: :button }
      %div.signup
        = link_to('Signup', new_user_registration_path)