config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :challenges

  get '/created_challenges', to: 'challenges#user_created_index', as: 'user_created_challenges'
  get '/add_test_case', to: 'challenges#add_test_case'

  post '/challenges/:id/add_to_user_list', to: 'user_challenges#create', as: 'new_user_challenge'
  post '/challenges/:id/submit', to: 'user_challenges#submit', as: 'user_challenge_submit'

  delete '/challenges/:id/remove_from_user_list', to: 'user_challenges#destroy', as: 'delete_user_challenge'

  patch 'challenges/:id/update_anki_dates', to: 'user_challenges#update_anki_dates', as: 'user_challenge_update_anki_dates'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if user_signed_in?
      @challenges = current_user.user_challenges.due_today
      render 'logged_in_show'
    else
      render 'show'
    end
  end
end

app/views/home/logged_in_show.html.haml
= provide(:title, current_user.username)
%div.row
  %div.medium-4.columns
    %div= link_to('Create a new challenge', new_challenge_path)
    %div= link_to('View Created Challenges', user_created_challenges_path)
    %div= link_to('View All Challenges', challenges_path)
  %div.medium-8.columns
    %h3 Today's Challenges
    %hr
    %ul
      - @challenges.each do |challenge|
        %li= link_to challenge.challenge.title, challenge.challenge

app/views/home/show.html.haml
%div.row
  %div.small-12.columns
    %h1  Welcome to Interview Anki

    %h3 Interview Anki??
    %h5 Interview Anki helps you study for a programming interview by using spaced repetition. Through interfacing with HackerRank, you can code your solutions in browser and retrieve fast responses.
    %ul
      %li Add existing challenges (or new ones you create!) to your deck to create your Anki system.
      %li Attempt and complete challenges.
      %li Once you complete a challenge, you'll decide when you want to see the challenge again.
      %ul
        %li Recently added challenges will provide shorter time spans (10 minutes, 1-5 days).
        %li Older challenges will offer more distant options (1 month, 3 months, 6 months).
    %br
    %h2.text-center= link_to 'Sign Up Now!', new_user_registration_path