config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :challenges

  get '/created_challenges', to: 'challenges#user_created_index', as: 'user_created_challenges'
  get '/add_test_case', to: 'challenges#add_test_case'

  post '/challenges/:id/add_to_user_list', to: 'user_challenges#create', as: 'new_user_challenge'
  post '/challenges/:id/submit', to: 'user_challenges#submit', as: 'user_challenge_submit'

  delete '/challenges/:id/remove_from_user_list', to: 'user_challenges#destroy', as: 'delete_user_challenge'

  patch 'challenges/:id/update_anki_dates', to: 'user_challenges#update_anki_dates', as: 'user_challenge_update_anki_dates'
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  validates :slug, presence: true, uniqueness: true

  has_many :user_challenges, dependent: :destroy
  has_many :users, through: :user_challenges
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  serialize :test_case_input, Array
  serialize :test_case_output, Array

  def test_cases
    self.test_case_input.zip(self.test_case_output)
  end

  def language_string
    languages = { 3 => 'Java', 5 => 'Python', 8 => 'Ruby' }
    languages[self.language]
  end

  def starter_code_raw
    @starter_code_raw = self.starter_code == nil ? nil : self.starter_code.inspect[1..-2]
  end

  def boilerplate_code_raw
    @boilerplate_code_raw = self.boilerplate_code == nil ? nil : self.boilerplate_code.inspect[1..-2]
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_challenge, only: [:show, :edit, :update, :destroy]
  before_action :language_options, only: [:new, :edit]
  before_action :authorize_user_to_edit, only: [:edit, :update, :destroy]

  def show
    user_challenge = current_user.user_challenges.find_by_challenge_id(params[:id])
    if user_challenge
      if user_challenge.due_today?
        flash.now[:notice] = 'This challenge is due today.'
      else
        flash.now[:error] = 'This challenge is not due today.'
      end
    else
      flash.now[:error] = 'You must save this challenge to your list if you wish to practice the challenge.'
    end
  end

  def index
    @challenges = Challenge.first(10)
  end

  def user_created_index
    @challenges = current_user.created_challenges.all
  end

  def new
    @challenge = current_user.challenges.new
  end

  def destroy
    if not @challenge.destroy
      flash[:error] = 'There was a problem deleting the challenge.'
    else
      flash[:notice] = 'Challenge deleted.'
    end
    redirect_to user_created_challenges_path
  end

  def add_test_case
    respond_to do |format|
      format.js { render '/challenges/add_test_case' }
    end
  end

  def create
    title = challenge_params[:title]
    slug = title.parameterize
    @challenge = current_user.created_challenges.new({ slug: slug }.merge(challenge_params))
    if @challenge.save
      flash[:notice] = 'Challenge has successfully been created.'
      redirect_to @challenge
    else
      flash[:error] = 'There was an error.'
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    title = challenge_params[:title]
    slug = title.parameterize
    if @challenge.update({ slug: slug }.merge(challenge_params))
      redirect_to @challenge
    else
      render :edit
    end
  end

  private
  def challenge_params
    params.require(:challenge).permit(:slug, :title, :description, :boilerplate_code, :starter_code, :language, :test_case_input=> [], :test_case_output => [])
  end

  def authorize_user_to_edit
    if @challenge.creator != current_user
      flash.now[:error] = 'You cannot modify a challenge you did not create.'
      redirect_to @challenge
    end
  end

  def find_challenge
    @challenge = Challenge.find_by_id(params[:id])
    if not @challenge
      flash[:error] = 'Challenge was not found.'
      redirect_to root_path
    end
  end

  def language_options
    @language_options = [['Python', 5], ['Ruby', 8], ['Java', 3]]
  end
end

app/views/challenges/_anki_dates.html.haml
%div.row
  = form_tag user_challenge_update_anki_dates_path, method: :patch do
    - anki_dates.each_with_index do |date, idx|
      %div.small-3.columns
        = button_tag date[0], { class: :button, value: idx }

app/views/challenges/_form.html.haml
%div.field
  = f.label :title
  = f.text_field :title, autofocus: true

%div.field
  = f.label :description
  = f.text_area :description, { class: 'description-area' }

%div.field
  = f.label :language
  = f.select :language, options_for_select(language_options)

%div.field
  = f.label :boilerplate_code
  = f.text_area :boilerplate_code, { class: 'boilerplate-area' }

%div.field
  = f.label :starter_code
  = f.text_area :starter_code, { class: 'code-area' }

%div.field
  = f.hidden_field :starter_code_raw

%div.field
  = f.hidden_field :boilerplate_code_raw

%div.field.test-cases
  - if challenge.test_case_input != []
    - challenge.test_cases.each do |tc|
      = render 'test_cases', tc: tc
  - else
    = render 'test_cases', tc: ['', '']

%div.field
  = link_to 'Add a test case', {action: 'add_test_case'} , { remote: true, class: 'button' }

app/views/challenges/_results.html.haml
%ul
  - results.each do |r|
    %li= r

app/views/challenges/_test_cases.html.haml
%table
  %tr
    %td
      %div.field
        = label_tag 'challenge_test_case_input', 'Test Case Input'
        = text_area_tag 'challenge[test_case_input][]', tc[0]
    %td
      %div.field
        = label_tag 'challenge_test_case_output', 'Test Case Output'
        = text_area_tag 'challenge[test_case_output][]', tc[1]

app/views/challenges/add_test_case.js.erb
$('.test-cases').append("<%= j render 'test_cases', tc: ['',''] %>");

app/views/challenges/edit.html.haml
= provide(:title, 'Edit Challenge')
%div.row
  %div.small-12.columns
    %h2 Edit Challenge
    = form_for(@challenge, url: { action: :update }, method: :patch) do |f|
      = render 'form', { f: f, language_options: @language_options, challenge: @challenge }
      %div.actions
        = f.submit 'Save', { class: :button }
        = link_to('Cancel', @challenge)

app/views/challenges/index.html.haml
= provide(:title, 'All Challenges')
%div.row
  %div.small-12.columns
    %h2 All Challenges
    - if @challenges
      %table
        - @challenges.each do |challenge|
          %tr
            %td= link_to challenge.title, challenge
            %td= link_to 'Edit', edit_challenge_path(challenge)
            %td= link_to 'Delete', challenge, { method: :delete, data: { confirm: 'Are you sure?' } }

app/views/challenges/new.html.haml
= provide(:title, 'New Challenge')
%div.row
  %div.small-12.columns
    %h2 Create new Challenge
    = form_for(@challenge, url: { action: :create }) do |f|
      = render 'form', { f: f, language_options: @language_options, challenge: @challenge }
      %div.actions
        = f.submit 'Submit', { class: :button }

app/views/challenges/show.html.haml
= provide(:title, @challenge.title)
%div.row
  %div.small-12.columns
    %div.row
      %div.medium-8.large-10.columns
        %h2= @challenge.title
      %div.medium-2.large-1.columns
        = button_to('Add', new_user_challenge_path, { class: 'button add-challenge' })
      %div.medium-2.large-1.columns
        = button_to('Remove', delete_user_challenge_path, { method: :delete, class: 'button add-challenge' })
    %h4= @challenge.description
    %h5#language= @challenge.language_string
    = form_tag(user_challenge_submit_path, { method: :post, remote: true }) do
      = label_tag(:code, 'Code')
      = text_area_tag(:code, @challenge.starter_code, { class: 'code-area' })
      = label_tag(:boilerplate, 'Boilerplate')
      = text_area_tag(:boilerplate, @challenge.boilerplate_code, { class: 'boilerplate-area', readonly: true })
      = label_tag(:test_cases, 'Test Cases')
      = text_area_tag(:test_case_input, @challenge.test_case_input, { readonly: true })
      = submit_tag('Run', { class: :button })
    %h4#results Results
    %h4#anki-dates

app/views/challenges/submit.js.erb
$('#results').html("<%= j render '/challenges/results', results: @results %>");
<% if @anki_dates %>
  $('#anki-dates').html("<%= j render '/challenges/anki_dates', anki_dates: @anki_dates %>")
<% end %>

app/views/challenges/user_created_index.html.haml
= provide(:title, 'Created Challenge')
%div.row
  %div.small-12.columns
    %h2 Created Challenges
    - if @challenges
      %table
        - @challenges.each do |challenge|
          %tr
            %td= link_to challenge.title, challenge
            %td= link_to 'Edit', edit_challenge_path(challenge)
            %td= link_to 'Delete', challenge, { method: :delete, data: { confirm: 'Are you sure?' } }